// decide() table-driven from fixtures/decision_matrix.json, generated by gen_fixtures.py from the
// QA harness's own evaluator (app/qa/checks/decision_matrix.py). Engine and QA cannot disagree.
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import * as engine from '@engine';
import { answersById, CONTENT_DIR, day, readJson } from './helpers';

const decide = (engine as any).decide as (s: any, d: Date) => any;
const summarisePlot = (engine as any).summarisePlot as (l: any[]) => any;
const fx = readJson(path.join(__dirname, '../fixtures/decision_matrix.json'));
const sha = (f: string) => createHash('sha256').update(readFileSync(path.join(CONTENT_DIR, f))).digest('hex');

function strings(v: any, out: string[] = []): string[] {
  if (typeof v === 'string') out.push(v);
  else if (Array.isArray(v)) v.forEach((x) => strings(x, out));
  else if (v && typeof v === 'object') Object.values(v).forEach((x) => strings(x, out));
  return out;
}

/** Every problem with a returned card, or [] when it is a faithful copy of answers.json[expected]. */
export function cardProblems(card: any, expected: string): string[] {
  const p: string[] = [];
  if (!card || typeof card !== 'object') return [`no card returned (${String(card)})`];
  if (card.id !== expected) p.push(`id ${card.id} != ${expected}`);
  const a = answersById.get(card.id);
  if (!a) return [...p, `card id ${card.id} is not in answers.json`];
  if (card.severity !== a.severity) p.push(`severity ${card.severity} != ${a.severity}`);
  for (const lang of ['sw', 'en'] as const) if (card.text?.[lang] !== a.text[lang]) p.push(`text.${lang} differs from answers.json`);
  if (card.text?.kik !== undefined && card.text.kik !== a.text.kik) p.push('text.kik differs from answers.json');
  if (a.not_sure) for (const lang of ['sw', 'en'] as const) if (a.not_sure[lang] && card.notSure?.[lang] !== a.not_sure[lang]) p.push(`notSure.${lang} missing or differs (answers.json not_sure)`);
  const allowed = new Set(strings(a));
  const audioRe = new RegExp(`^/audio/(sw|kik|en)/${card.id}\\.mp3$`);
  for (const s of strings(card)) if (!allowed.has(s) && !audioRe.test(s) && !['sw', 'kik', 'en'].includes(s)) p.push(`text not in answers.json: "${s.slice(0, 60)}"`);
  for (const [lang, url] of Object.entries(card.audio ?? {})) if (url !== `/audio/${lang}/${card.id}.mp3`) p.push(`audio.${lang} = ${String(url)}`);
  if (!Array.isArray(card.sources)) p.push('sources is not an array');
  if (typeof card.assumption !== 'boolean') p.push('assumption is not a boolean');
  return p;
}

describe('decide: fixtures are current', () => {
  it('fixtures were generated from the rules.json and answers.json under test', () => {
    expect(fx.rules_sha256, 'rules.json changed: run python3 gen_fixtures.py').toBe(sha('rules.json'));
    expect(fx.answers_sha256, 'answers.json changed: run python3 gen_fixtures.py').toBe(sha('answers.json'));
  });
  it('the QA evaluator produced the fixtures (not the fallback port)', () => {
    expect(fx.evaluator).toMatch(/^qa\.checks\.decision_matrix/);
  });
  it('every expected answer id exists in answers.json', () => expect(fx.expected_ids_missing_from_answers).toEqual([]));
  it('decide is exported', () => expect(typeof decide).toBe('function'));
});

describe(`decide: ${fx.count} QA decision-matrix cases`, () => {
  const groups = new Map<string, any[]>();
  for (const c of fx.cases) {
    const k = `${c.summary.dominant} / ${c.window}`;
    groups.set(k, [...(groups.get(k) ?? []), c]);
  }
  for (const [k, cases] of groups) {
    it(`${k} (${cases.length} cases)`, () => {
      const bad: string[] = [];
      for (const c of cases) {
        let card: any;
        try { card = decide(structuredClone(c.summary), day(c.date)); } catch (e) { card = `threw ${(e as Error).message}`; }
        const p = cardProblems(card, c.expected);
        if (p.length) bad.push(`affected=${c.summary.affected} uncertain=${c.summary.uncertain} distinct=${c.summary.distinctProblems} ${c.date}: ${p.join('; ')}`);
      }
      expect(bad.slice(0, 6), `${bad.length} of ${cases.length} cases wrong`).toEqual([]);
    });
  }
});

describe(`decide(summarisePlot(leaves)): ${fx.pipeline.length} pipeline cases`, () => {
  it('summarisePlot then decide gives the QA answer on real leaf lists', () => {
    const bad: string[] = [];
    for (const c of fx.pipeline) {
      const ls = c.leaves.map((label: string) => ({ label, probs: {}, confidence: label === 'unsure' ? 0.4 : 0.9, quality: { ok: true, blur: 100, brightness: 0.5 }, abstained: label === 'unsure', modelVersion: 'fixture' }));
      let card: any;
      try { card = decide(summarisePlot(ls), day(c.date)); } catch (e) { card = `threw ${(e as Error).message}`; }
      const p = cardProblems(card, c.expected);
      if (p.length) bad.push(`${JSON.stringify(c.leaves)} ${c.date}: ${p.join('; ')}`);
    }
    expect(bad.slice(0, 6), `${bad.length} of ${fx.pipeline.length} wrong`).toEqual([]);
  });
});

describe('decide: garbage input gives ask_officer', () => {
  const ok = fx.cases.find((c: any) => c.expected === 'healthy_all').summary;
  const garbage: [string, any, Date][] = [
    ['null summary', null, day('2026-10-04')],
    ['undefined summary', undefined, day('2026-10-04')],
    ['empty object', {}, day('2026-10-04')],
    ['string summary', 'rust', day('2026-10-04')],
    ['unknown dominant', { ...ok, dominant: 'banana' }, day('2026-10-04')],
    ['NaN affected', { ...ok, affected: NaN }, day('2026-10-04')],
    ['negative uncertain', { ...ok, uncertain: -1 }, day('2026-10-04')],
    ['string counts', { ...ok, affected: '3', uncertain: '0' }, day('2026-10-04')],
    ['Infinity n', { ...ok, n: Infinity }, day('2026-10-04')],
    ['invalid date', ok, new Date('not a date')],
  ];
  it.each(garbage)('%s', (_name, s, d) => {
    let card: any;
    expect(() => { card = decide(s, d); }).not.toThrow();
    expect(cardProblems(card, 'ask_officer')).toEqual([]);
  });
});

describe('decide: pure and read-only', () => {
  it('same input twice gives the same card and the summary is not mutated', () => {
    const c = fx.cases.find((x: any) => x.expected === 'rust_high_pre_rains');
    const s = structuredClone(c.summary);
    const a = decide(s, day(c.date));
    const b = decide(s, day(c.date));
    expect(a).toEqual(b);
    expect(s).toEqual(c.summary);
  });
});
